export const ZH_FONTS = ['Kaiti', 'Ma Shan Zheng', 'Noto Serif Simplified Chinese', 'SimSun'];

export const EN_FONTS = [
  'Arial',
  'Arial Black',
  'Bahnschrift',
  'Calibri',
  'Comic Sans MS',
  'Consolas',
  'Constantia',
  'Courier New',
  'Franklin Gothic Medium',
  'Gabriola',
  'Georgia',
  'Impact',
  'Ink Free',
  'MS Gothic',
  'MV Boli',
  'Segoe Print',
  'Segoe Script',
  'Segoe UI',
  'Tahoma',
  'Times New Roman',
  'Verdana',
  'Yu Gothic',
];
